makeRoot{Plot,Macro}: Add ghostscriptifyPDF call, handle includes.
Include-handling is simple - just include (named macros) or gInterpreter->LoadFile()
is accepted if normal double quotes are used.
Only relative paths to the macro dir are checked.

diff --git a/makeRootMacro b/makeRootMacro
--- a/makeRootMacro
+++ b/makeRootMacro
@@ -15,8 +15,30 @@ fi
 # if we are newer...
 test ${0} -nt ${OUTPUTNAME} && REMAKE=1
 
+# if ghostscriptifyPDF is newer...
+test ghostscriptifyPDF -nt ${OUTPUTNAME} && REMAKE=1
+
 # if input is newer...
 test ${MACRONAME} -nt ${OUTPUTNAME} && REMAKE=1
+
+# Dependencies, it's C++, sort of!
+OLD_IFS=${IFS}
+IFS=$'\n'
+NAMED_MACRO_DEPS=$(grep -E '#\s*include\s+"([^>]*)"' ${MACRONAME}                  | sed -n -e 's/.*[^"]*["]\([^"]\+\)["].*/\1/p')
+UNNAMED_MACRO_DEPS=$(grep -E '\s*gInterpreter->LoadFile\("([^"]*)"\)' ${MACRONAME} | sed -n -e 's/.*[^"]*["]\([^"]\+\)["].*/\1/p')
+MACRO_BASE_DIR=$(dirname ${MACRONAME})
+
+for DEP in ${NAMED_MACRO_DEPS}; do
+		if [[ ! "${DEP}" =~ ^/ ]]; then
+				test "${MACRO_BASE_DIR}/${DEP}" -nt ${OUTPUTNAME} && REMAKE=1
+		fi
+done
+for DEP in ${UNNAMED_MACRO_DEPS}; do
+		if [[ ! "${DEP}" =~ ^/ ]]; then
+				test "${MACRO_BASE_DIR}/${DEP}" -nt ${OUTPUTNAME} && REMAKE=1
+		fi
+done
+IFS=${OLD_IFS}
 
 if [ ${REMAKE} -eq 1 ]; then
 		echo "Need to remake ${OUTPUTNAME}..."
@@ -29,4 +51,13 @@ else
 fi
 
 root -q -b -l ${MACRONAME}+
+
+if [ $? -eq 0 ]; then
+		echo "Remaking ${OUTPUTNAME} went well."
+		./ghostscriptifyPDF ${OUTPUTNAME}
+else
+		echo "Remaking of ${OUTPUTNAME} failed, removing it!"
+		rm ${OUTPUTNAME}
+fi
+
 popd > /dev/null
diff --git a/makeRootPlot b/makeRootPlot
--- a/makeRootPlot
+++ b/makeRootPlot
@@ -15,7 +15,7 @@ else
 		REMAKE=1
 fi
 
-# Parse filename.
+# Parse filename. 
 WIDTH=1000
 HEIGHT=600
 
@@ -40,12 +40,34 @@ MACRONAME="${NAMEPART}.C"
 # if we are newer...
 test ${0} -nt ${OUTPUTNAME} && REMAKE=1
 
+# if ghostscriptifyPDF is newer...
+test ghostscriptifyPDF -nt ${OUTPUTNAME} && REMAKE=1
+
 # if input is newer...
 test ${MACRONAME} -nt ${OUTPUTNAME} && REMAKE=1
 # if style is newer...
 test ${STYLEFILE} -nt ${OUTPUTNAME} && REMAKE=1
 # if plotter is newer...
 test ${PLOTTER} -nt ${OUTPUTNAME} && REMAKE=1
+
+# Dependencies, it's C++, sort of!
+OLD_IFS=${IFS}
+IFS=$'\n'
+NAMED_MACRO_DEPS=$(grep -E '#\s*include\s+"([^>]*)"' ${MACRONAME}                  | sed -n -e 's/.*[^"]*["]\([^"]\+\)["].*/\1/p')
+UNNAMED_MACRO_DEPS=$(grep -E '\s*gInterpreter->LoadFile\("([^"]*)"\)' ${MACRONAME} | sed -n -e 's/.*[^"]*["]\([^"]\+\)["].*/\1/p')
+MACRO_BASE_DIR=$(dirname ${MACRONAME})
+
+for DEP in ${NAMED_MACRO_DEPS}; do
+		if [[ ! "${DEP}" =~ ^/ ]]; then
+				test "${MACRO_BASE_DIR}/${DEP}" -nt ${OUTPUTNAME} && REMAKE=1
+		fi
+done
+for DEP in ${UNNAMED_MACRO_DEPS}; do
+		if [[ ! "${DEP}" =~ ^/ ]]; then
+				test "${MACRO_BASE_DIR}/${DEP}" -nt ${OUTPUTNAME} && REMAKE=1
+		fi
+done
+IFS=${OLD_IFS}
 
 ROOTFILE=${NAMEPART}.root
 if [ -e ${ROOTFILE} ]; then
@@ -66,3 +88,12 @@ else
 fi
 
 root -x -b -l ${PLOTTER}"(\"${NAMEPART}\", \"${OUTPUTNAME}\", ${HAVEROOTFILE}, ${WIDTH}, ${HEIGHT}, \"${STYLEFILE}\", \"${STYLENAME}\")"
+if [ $? -eq 0 ]; then
+		echo "Remaking ${OUTPUTNAME} went well."
+		if [[ "${OUTPUTNAME}" == *.pdf ]]; then
+				./ghostscriptifyPDF ${OUTPUTNAME}
+		fi
+else
+		echo "Remaking of ${OUTPUTNAME} failed, removing it!"
+		rm ${OUTPUTNAME}
+fi
